apiVersion: v1
kind: Service
metadata:
  labels:
    app: techtrends
  name: techtrends
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
{{- with .Values.service }}
  - port: {{ .port }}
    protocol: {{ .protocol }}
    targetPort: {{ default .port .targetPort }}
  selector:
    app: techtrends
  type: {{ .type }}
{{- end }}
